"""empty message

Revision ID: f396aa7f9264
Revises: 3f29274ea363
Create Date: 2024-12-03 14:25:05.235237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f396aa7f9264'
down_revision = '3f29274ea363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_booking_id_review', 'bookings', ['booking_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_booking_id_review', type_='foreignkey')
        batch_op.drop_column('booking_id')

    # ### end Alembic commands ###
